name: Deploy to staging

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello from Github Actions!"